theme: jekyll-theme-cayman
title: Neural Network Compression using Reinforcement Learning
description: Capstone Project of Gaurav Mittal, Shashank Tripathi, Yi Jiang under Dr. Kris Kitani and Amazon Lab126
